name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: action/checkout@v2
      - name: Staring Node.js ${{matrix.node-version}}
        uses: action/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      # - name: install modules
      #   run: npm install
      # - name: build production project
      #   run: npm run build:prod
      # - name: linting typescript
      #   run: npm run lint:ts
      # - name: linting css
      #   run: npm run lint:css
      # - name: unit testing
      #   run: npm run test:unit

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3 - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3